spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.0.124/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wx7af0feed355ea0dc
  mpAppPayId: wxd898fcb01713c658
  mpAppSecret: 7fe16124474860430fa8862deabddca9
  mchId: 1483469312
  mchKey: C5245D70627C1F8E9964D494B0735025
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://demosell.natapp1.cc/sell/pay/notify
